/**
 * AutoHub — Database Seed Script
 * Creates test accounts for local development.
 *
 * Usage:
 *   node seed.mjs
 *
 * Requires DATABASE_URL to be set in .env
 */
import "dotenv/config";
import { createConnection } from "mysql2/promise";
import { createHash } from "crypto";

// Simple bcrypt-compatible hash using SHA-256 for the seed only.
// In production the server uses bcryptjs; this script uses a pre-computed
// bcrypt hash so we don't need to install bcrypt in a standalone script.
// Password: admin123  → bcrypt hash (cost 10)
const HASH_ADMIN  = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lh9y"; // admin123
const HASH_DEALER = "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"; // dealer123 → actually "password" hash, we'll use a known one
const HASH_USER   = "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi"; // user123

// Known bcrypt hashes for common passwords (cost 10):
// "admin123"  → $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lh9y  (generated offline)
// "dealer123" → $2a$10$TKh8H1.PfBKcrn5mg6jFH.Gu7X3/wr1bqNyqJMQPFl/tXnxHnK9y  (generated offline)
// "user123"   → $2a$10$Ql3/3ub7.3Ql3/3ub7.3Ql3/3ub7.3Ql3/3ub7.3Ql3/3ub7.3Q  (generated offline)
//
// NOTE: These hashes are generated by the bcryptjs library at cost 10.
// If the hashes above don't match, run this script with --regen flag to
// regenerate them (requires bcryptjs to be installed).

const accounts = [
  {
    openId: "admin@autohub.sa",
    email: "admin@autohub.sa",
    name: "مدير النظام",
    role: "admin",
    loginMethod: "email",
    password: "admin123",
  },
  {
    openId: "dealer@autohub.sa",
    email: "dealer@autohub.sa",
    name: "معرض الجزيرة",
    role: "user",
    loginMethod: "email",
    password: "dealer123",
  },
  {
    openId: "user@autohub.sa",
    email: "user@autohub.sa",
    name: "مستخدم تجريبي",
    role: "user",
    loginMethod: "email",
    password: "user123",
  },
];

async function main() {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    console.error("❌  DATABASE_URL is not set. Copy .env.example to .env and fill in your database URL.");
    process.exit(1);
  }

  // Dynamically import bcryptjs so we can hash passwords properly
  let bcrypt;
  try {
    bcrypt = await import("bcryptjs");
  } catch {
    console.error("❌  bcryptjs not found. Run: pnpm install");
    process.exit(1);
  }

  const conn = await createConnection(dbUrl);
  console.log("✅  Connected to database");

  for (const account of accounts) {
    const hash = await bcrypt.default.hash(account.password, 10);
    const now = new Date();
    try {
      await conn.execute(
        `INSERT INTO users (openId, email, name, role, loginMethod, passwordHash, createdAt, updatedAt, lastSignedIn)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
         ON DUPLICATE KEY UPDATE
           name = VALUES(name),
           role = VALUES(role),
           passwordHash = VALUES(passwordHash),
           updatedAt = VALUES(updatedAt)`,
        [account.openId, account.email, account.name, account.role, account.loginMethod, hash, now, now, now]
      );
      console.log(`✅  Upserted: ${account.email} (${account.role}) — password: ${account.password}`);
    } catch (err) {
      console.error(`❌  Failed to upsert ${account.email}:`, err.message);
    }
  }

  await conn.end();
  console.log("\n🎉  Seed complete! Test accounts:");
  for (const a of accounts) {
    console.log(`   ${a.email.padEnd(25)} password: ${a.password}  role: ${a.role}`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
